### ISSUE TITLE
Restart inversions at a particular pixel

### ISSUE THREAD

**Issue by ckuckein** [aasensio/hazel2#20]
When running Hazel 2 on a cluster, it would be very helpful to have the following 2 features:

1. If the cluster runs into the 'walltime' without finishing to invert the whole map, it would be good to restart the inversions from that point (from the last inverted pixel).

2. In general, be able to restart the inversions (in a cluster) from a given pixel position in the map. 

Thanks!

**Comment by aasensio** [comment]
The `run_all_pixels` method from `Iterator` now accepts two keywords: `start` that defines the first pixel to consider in the inversions and `end` that defines the last pixel. They are by default set to 0 and `None`, so that all pixels are inverted. If you want to do the inversion of all pixels, just use `run_all_pixels()`.
